### ISSUE TITLE
4.3.6 cpu占用过高

### ISSUE THREAD

**Issue by 6X5znRTxY8Xo6E** [nevinen/dockerfiles#1]
e大，之前用的4.3.5。今天升了4.3.6。armv8版。
ps进程里这个一直卡cpu 100% /bin/bash /usr/local/bin/tracker-error
查询日志卡在这 crond[307]: USER root pid 344 cmd tracker-error
而且这个版本启动也很慢，大概要8到10分钟才能开能webui。日志如下：
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 10-addpackge: executing... 

[cont-init.d] 10-addpackge: exited 0.

[cont-init.d] 20-mkdir: executing... 

[cont-init.d] 20-mkdir: Make some folders...

[cont-init.d] 20-mkdir: exited 0.

[cont-init.d] 30-config: executing... 

[cont-init.d] 30-config: Overriding required parameters...

[cont-init.d] 30-config: exited 0.

[cont-init.d] 40-fixuser: executing... 

[cont-init.d] 40-fixuser: Change owner to user qbittorrent...

[cont-init.d] 40-fixuser: PUID=1500

[cont-init.d] 40-fixuser: PGID=1500

[cont-init.d] 40-fixuser: usermod: no changes

[cont-init.d] 40-fixuser: exited 0.

[cont-init.d] 50-crontab: executing... 

[cont-init.d] 50-crontab: Set crontab to system...

[cont-init.d] 50-crontab: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

**Comment by nevinen** [comment]
4.3.6应该是优化了资源占用啊，你是不刚好在启动时遇到了马上执行cron中tracker-error这个检查tracker错误的任务？

另上，其他时间启动问题复现么
