### ISSUE TITLE
qb配置tg推送失败

### ISSUE THREAD

**Issue by lqrqw** [nevinen/dockerfiles#1]
root@qbittorrent:/data $ notify
/usr/local/bin/notify: line 29: perl: command not found
(W) 2021-06-02T17:18:18 - [notify] 发送Telegram通知失败，错误代码：，错误消息：

(N) 2021-06-02T17:18:19 - [notify] 发送爱语飞飞通知成功

E大，
冒昧打扰。我是从灯大(80x86)转到你的镜像。4.3.5镜像试用了三个小时左右。一切正常，除了这个tg推送。上网环境应该没问题，平时是路由器开gfw模式。测试的时候开了全局，还是不行。环境变量也检查过了。镜像非常棒，比老灯的多了推送通知，加了python环境。镜像竟然还比老灯的略小。谢谢

**Comment by nevinen** [comment]
如果不要python还能再小三分之一，已经很小了．

刚刚又更新了一下，修复了报perl错误的问题．

不过似乎你发送不了TG消息和这个错误关系不大，你可以进入容器后手动依次运行下面的命令看看具体错误：

```
user_id="你的telegram user id"
bot_token="你bot的token"
message="消息内容"
curl -Ss -H "Content-Type:application/x-www-form-urlencoded" -X POST -d "chat_id=${user_id}&text=${message}&disable_web_page_preview=true" "https://api.telegram.org/bot${bot_token}/sendMessage"
```

**Comment by nevinen** [comment]
18:25左右的镜像把edu的问题解决了

**Comment by lqrqw** [comment]
谢谢e大热心帮助。问题解决了。本人没有细心看readme造成的。tg测试的时候，notify需要加两个参数。（notify "测试消息标题" "测试消息通知内容"）爱语飞飞不需要加这两个参数，能测试成功。所以造成了困惑，误以为tg推送有问题。实在是抱歉。
