### ISSUE TITLE
请教下，如何单独把下载目录映射到挂载的硬盘上

### ISSUE THREAD

**Issue by github-xihe** [nevinen/dockerfiles#10]
运行主机的硬盘是固态硬盘，挂载了一块移动硬盘，我想把默认下载目录downloads映射到挂载的移动硬盘，其他配置保留在固态硬盘里面，不知道下面这样可行不？

volumes:
      - ./data:/data
      - /mnt/hdisk/downloads:/data/downloads

**Comment by nevinen** [comment]
可以的。其实你也可以不使用默认下载目录，比如你映射为 /mnt/hdisk/downloads:/movies 然后qb中下载到/movies也是一样的。

**Comment by github-xihe** [comment]
> 可以的。其实你也可以不使用默认下载目录，比如你映射为 /mnt/hdisk/downloads:/movies 然后qb中下载到/movies也是一样的。

好的，谢谢
