### ISSUE TITLE
老哥,发送通知 log显示发送成功 实际上未收到

### ISSUE THREAD

**Issue by braless** [nevinen/dockerfiles#2]
![image](https://user-images.githubusercontent.com/38938679/124425467-2d067780-dd9b-11eb-9f7f-aa4c682914b0.png)

**Comment by braless** [comment]
我 是本地主机, 没有ssl证书,,(ps:世界真小-----From a  v4 user)

**Comment by nevinen** [comment]
一个小失误，随qb的下一个版本修复．

你急的话手动改一下容器内的`/usr/local/bin/notify`，将第45行中的`https`改为`http`．

**Comment by braless** [comment]
不急我换丁丁了,iyuu也可以不用

**Comment by braless** [comment]
还有个问题 我测试了一个种子 下载完成 没有发送通知,执行docker exec qbittorrent dl-finish <hash> 才发送通知, 我在dc里面 设置的dl 那个为true

**Comment by nevinen** [comment]
你是不是把qb设置中 下载->Torrent 完成时运行外部程序 中的`dl-finish "%I"`删除了，或者禁用`Torrent 完成时运行外部程序`功能了？

你可以从控制台日志中看到发没发：`docker logs qbittorrent`

![image](https://user-images.githubusercontent.com/83165391/124429181-20d0e900-dda0-11eb-86df-46b0e7a27afc.png)

**Comment by braless** [comment]
ok 收到了  感谢指导,!
